### ISSUE TITLE
Disarming not Working

### ISSUE THREAD

**Issue by ariel-elbit** [Intelligent-Quads/iq_gnc#3]
Hi,
I'm using the iq_gnc project to control my drone using arducopter pixhawk. When I kill the program before it exits on its' own, meaning if I use ctrl-c to kill to ROS node, I loose control over the drone and I'm am unable to disarm the motors. When attempting disarming using QGC I get an error arm/disarm failed. The only thing that works is rosrun mavros mavsafety kill.
I want to know before takeoff that I won't loose complete control over the drone.
Any help will be much appreciated.
Thanks a lot for your help,
Ariel

**Comment by ericjohnson97** [comment]
Dnag! I'm sorry about your drone.  It seems like you are using the code in a way that I did not consider when designing it.  The method in which my friends and I tested our drone was in conjunction with an RC controller. This controller had direct link to the FCU. If we wanted to revert to manual mode, we would simply change the flight mode out of guided, to a manual mode, which effectively removes all authority from the companion computer.  If you really want to only control via QGC and mavros then before you kill mavros you can switch the flight mode to loiter so the drone stops accepting commands from mavros. I would gamble to say that when killing the ROS node causes mavros to mess up and send garbage mavlink messages to the drone.    

let me know if this helps

**Comment by ariel-elbit** [comment]
First of all thanks for getting back so quickly. 
I am also using an RC controller but that's only for safety reasons, my goal is only to use the code and if needed QGC or mission planner. I saw that if I change the mode to either acro or drift I am able to disarm with the QGC. The main thing I want to know is that if I use the RTL from the QGC it will work and I won't have to count only on the RC controller.
Any thoughts?
Thanks again

**Comment by ericjohnson97** [comment]
that should work. The iq_gnc functions are only able to the command the drone when it is in guided. If you want to prove this to yourself, I would recommend spinning up a gazebo world and running the scenario in sim. This way you don't accidently break another drone :)
