### ISSUE TITLE
Python Version of this API

### ISSUE THREAD

**Issue by Sahas-Ananth** [Intelligent-Quads/iq_gnc#4]
Hey I would like to contribute to this project by creating a python version of this API to help with people who use python to write ROS. How would I do that?

I will do the following things: 
- [x] API in python2 with inline documentation.
- [x] Example programs/solutions in python2.

System used to check Ubuntu 18.04 running ROS Melodic Morenia with python2.

**Comment by ericjohnson97** [comment]
I think this would be very interesting.  If you like, I can add you as a contributor and you can start pushing your code to a dev branch. I will try and support this effort as much as I can.

**Comment by Sahas-Ananth** [comment]
Hey @ericjohnson97 Thanks for getting back to me so quickly. And yes I would love to be a collaborator in this project. I'll create a python2-dev branch and start pushing as soon as you make me a collaborator. Further I have couple of doubts on the API itself so if you can tell me some way I can chat with you and fix my queries that will be perfect.

**Comment by ericjohnson97** [comment]
you now are a contributor. Let me know any questions you might have about the code!

**Comment by Sahas-Ananth** [comment]
Thanks I'll start push th API code immediately. Is there any other way (instagram, reddit, email) I can talk to you to resolve my doubts about the code and close this issue? My socials are on my github page if you want to reach out.

**Comment by ericjohnson97** [comment]
Sorry about that. Here is the link to my discord. Feel free to post there or dm me https://discord.gg/VCcRyVpPEs
